version: '3'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - library-network

  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: ${APP_ENV}
    command: sh -c "yarn typeorm:migration:run && yarn run start:dev"  
    depends_on:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - library-network

networks:
  library-network:
